---
detectors:
  IrresponsibleModule:
    enabled: false
  TooManyStatements:
    enabled: true
    max_statements: 15
  DuplicateMethodCall:
    enabled: false
  UncommunicativeVariableName:
    enabled: false
  UncommunicativeParameterName:
    enabled: false
  UtilityFunction:
    public_methods_only: true
